if (NOT OPENSSL_NO_ASM)
    if (${ARCH} STREQUAL "x86")
        set(PL_ASM e_padlock-x86.S)
    elseif (${ARCH} STREQUAL "x86_64")
        set(PL_ASM e_padlock-x86_64.s)
    endif ()
endif ()

# If invoked from crypto/CMakeLists, get the static engines.
function (engines_for_crypto_lib)
    set(SOURCE)
    if (NOT OPENSSL_NO_PADLOCKENG)
        list(APPEND SOURCE ../engines/e_padlock.c)
        if (DEFINED PL_ASM)
            list(APPEND SOURCE ${PL_ASM})
            target_compile_definitions(crypto PUBLIC PADLOCKASM)
        endif ()
    endif ()
    if (NOT OPENSSL_NO_CAPIENG)
        list(APPEND SOURCE ../engines/e_capi.c)
    endif ()
    if (NOT OPENSSL_NO_AFALGENG)
        list(APPEND SOURCE ../engines/e_afalg.c)
    endif ()
    if (NOT OPENSSL_NO_DEVCRYPTOENG)
        list(APPEND SOURCE ../engines/e_devcrypto.c)
    endif ()
    target_sources(crypto PRIVATE ${SOURCE})
endfunction ()
