macro(hurd_generic32)
    base_unix()
    set(CFLAGS_DEBUG -Wall -O0 -g)
    set(CFLAGS_RELEASE -Wall -O3)
    #? cflags           => threads("-pthread"),
    target_link_libraries(crypto -pthread)
    set(BN_LLONG 1)
    set(RC4_CHAR 1)
endmacro ()

macro(hurd_generic64)
    hurd_generic32()
    set(SIXTY_FOUR_BIT_LONG 1)
    set(RC4_CHAR 1)
endmacro ()

macro(hurd_x86)
    hurd_generic32()
    set(CFLAGS_RELEASE ${CFLAGS_RELEASE} -fomit-frame-pointer)
    set(CFLAGS ${CFLAGS} -m32)
    set(BN_LLONG 1)
    set(PERLASM_SCHEME elf)
endmacro ()

macro(hurd_x86_64)
    hurd_generic64()
    set(CFLAGS ${CFLAGS} -m64)
    set(SIXTY_FOUR_BIT_LONG 1)
    set(PERLASM_SCHEME elf)
endmacro ()
