macro(disable x)
    set(OPENSSL_NO_${x} 1)
endmacro ()

macro(OpenSSLDefaults)
    # Default settings from Configure
    set(INSTALLPREFIX /usr/local)
    set(OPENSSLDIR ${INSTALLPREFIX}/ssl)
    set(MODULESDIR ${INSTALLPREFIX}/ossl-modules)
    set(ENGINESDIR ${INSTALLPREFIX}/engines-3)
    set(OPENSSL_NO_SHARED 0)

    # These are the items that OpenSSL disables by default
    disable(FIPS)
    disable(ASAN)
    disable(BROTLI)
    disable(BROTLI_DYNAMIC)
    disable(BUILDTEST_CXX)
    #disable(CRYPTO_MDEBUG)
    #disable(CRYPTO_MDEBUG_BACKTRACE)
    disable(DEVCRYPTOENG)
    disable(EC_NISTP_64_GCC_128)
    disable(EGD)
    disable(EXTERNAL_TESTS)
    disable(FUZZ)
    disable(PIE)
    disable(JITTER)
    disable(KTLS)
    disable(MD2)
    disable(MSAN)
    disable(RC5)
    disable(SCTP)
    disable(SSL3)
    disable(SSL3_METHOD)
    disable(SSLKEYLOG)
    disable(TFO)
    #disable(TRACE)
    disable(UBSAN)
    disable(UNIT_TEST)
    disable(WEAK_SSL_CIPHERS)
    disable(ZLIB)
    disable(ZLIB_DYNAMIC)
    disable(ZSTD)
    disable(ZSTD_DYNAMIC)
    disable(FIPS)
    disable(RC4)
    disable(LEGACY)
    disable(TFO)
    disable(MODULE)
endmacro ()
